version: "3"

# There are no volumes, because the data can be deleted after shutting
# down the containers.
services:
    postgres:
        build: .
        env_file:
            - ./.env
        ports:
          - "5432:5432"
